// Code generated by protoc-gen-go.
// source: raft.proto
// DO NOT EDIT!

/*
Package rpb is a generated protocol buffer package.

It is generated from these files:
	raft.proto

It has these top-level messages:
	Nodes
	AppendRequest
	VoteRequest
	Entry
	Node
	Response
	Ack
*/
package rpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Nodes struct {
	SenderID uint64  `protobuf:"varint,1,opt,name=senderID" json:"senderID,omitempty"`
	Nodes    []*Node `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *Nodes) Reset()                    { *m = Nodes{} }
func (m *Nodes) String() string            { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()               {}
func (*Nodes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Nodes) GetSenderID() uint64 {
	if m != nil {
		return m.SenderID
	}
	return 0
}

func (m *Nodes) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type AppendRequest struct {
	// sender ID
	SenderID uint64 `protobuf:"varint,1,opt,name=senderID" json:"senderID,omitempty"`
	// leaders term
	Term uint64 `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
	// leader ID
	LeaderID uint64 `protobuf:"varint,3,opt,name=leaderID" json:"leaderID,omitempty"`
	// index of log entry immediately preceding new ones
	PrevLogIdx uint64 `protobuf:"varint,4,opt,name=prevLogIdx" json:"prevLogIdx,omitempty"`
	// term of prevLogIdx entry
	PrevLogTerm uint64 `protobuf:"varint,5,opt,name=prevLogTerm" json:"prevLogTerm,omitempty"`
	// leader commit index
	LeaderCommitIdx uint64 `protobuf:"varint,6,opt,name=leaderCommitIdx" json:"leaderCommitIdx,omitempty"`
	// log entries to commit
	Entries []*Entry `protobuf:"bytes,7,rep,name=entries" json:"entries,omitempty"`
}

func (m *AppendRequest) Reset()                    { *m = AppendRequest{} }
func (m *AppendRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendRequest) ProtoMessage()               {}
func (*AppendRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppendRequest) GetSenderID() uint64 {
	if m != nil {
		return m.SenderID
	}
	return 0
}

func (m *AppendRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendRequest) GetLeaderID() uint64 {
	if m != nil {
		return m.LeaderID
	}
	return 0
}

func (m *AppendRequest) GetPrevLogIdx() uint64 {
	if m != nil {
		return m.PrevLogIdx
	}
	return 0
}

func (m *AppendRequest) GetPrevLogTerm() uint64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendRequest) GetLeaderCommitIdx() uint64 {
	if m != nil {
		return m.LeaderCommitIdx
	}
	return 0
}

func (m *AppendRequest) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type VoteRequest struct {
	// candidate term
	Term uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	// sender's ID, the candidate
	CandidateID uint64 `protobuf:"varint,2,opt,name=candidateID" json:"candidateID,omitempty"`
	// last log entry information
	LastLogIdx  uint64 `protobuf:"varint,3,opt,name=lastLogIdx" json:"lastLogIdx,omitempty"`
	LastLogTerm uint64 `protobuf:"varint,4,opt,name=lastLogTerm" json:"lastLogTerm,omitempty"`
}

func (m *VoteRequest) Reset()                    { *m = VoteRequest{} }
func (m *VoteRequest) String() string            { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()               {}
func (*VoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VoteRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteRequest) GetCandidateID() uint64 {
	if m != nil {
		return m.CandidateID
	}
	return 0
}

func (m *VoteRequest) GetLastLogIdx() uint64 {
	if m != nil {
		return m.LastLogIdx
	}
	return 0
}

func (m *VoteRequest) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type Entry struct {
	Term    uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Idx     uint64 `protobuf:"varint,2,opt,name=idx" json:"idx,omitempty"`
	Command []byte `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Entry) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Entry) GetIdx() uint64 {
	if m != nil {
		return m.Idx
	}
	return 0
}

func (m *Entry) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

type Node struct {
	ID   uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Node) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Node) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type Response struct {
	SenderID       uint64 `protobuf:"varint,1,opt,name=senderID" json:"senderID,omitempty"`
	Error          string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Accepted       bool   `protobuf:"varint,3,opt,name=accepted" json:"accepted,omitempty"`
	Term           uint64 `protobuf:"varint,4,opt,name=term" json:"term,omitempty"`
	LeaderID       uint64 `protobuf:"varint,5,opt,name=leaderID" json:"leaderID,omitempty"`
	LastAppliedIdx uint64 `protobuf:"varint,6,opt,name=lastAppliedIdx" json:"lastAppliedIdx,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Response) GetSenderID() uint64 {
	if m != nil {
		return m.SenderID
	}
	return 0
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func (m *Response) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Response) GetLeaderID() uint64 {
	if m != nil {
		return m.LeaderID
	}
	return 0
}

func (m *Response) GetLastAppliedIdx() uint64 {
	if m != nil {
		return m.LastAppliedIdx
	}
	return 0
}

type Ack struct {
	SenderID uint64 `protobuf:"varint,1,opt,name=senderID" json:"senderID,omitempty"`
}

func (m *Ack) Reset()                    { *m = Ack{} }
func (m *Ack) String() string            { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()               {}
func (*Ack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Ack) GetSenderID() uint64 {
	if m != nil {
		return m.SenderID
	}
	return 0
}

func init() {
	proto.RegisterType((*Nodes)(nil), "rpb.Nodes")
	proto.RegisterType((*AppendRequest)(nil), "rpb.AppendRequest")
	proto.RegisterType((*VoteRequest)(nil), "rpb.VoteRequest")
	proto.RegisterType((*Entry)(nil), "rpb.Entry")
	proto.RegisterType((*Node)(nil), "rpb.Node")
	proto.RegisterType((*Response)(nil), "rpb.Response")
	proto.RegisterType((*Ack)(nil), "rpb.Ack")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Raft service

type RaftClient interface {
	AppendEntries(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*Response, error)
	RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*Response, error)
	Join(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Nodes, error)
	ClusterState(ctx context.Context, in *Nodes, opts ...grpc.CallOption) (*Nodes, error)
	Leave(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Ack, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/rpb.Raft/AppendEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/rpb.Raft/RequestVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) Join(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Nodes, error) {
	out := new(Nodes)
	err := grpc.Invoke(ctx, "/rpb.Raft/Join", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) ClusterState(ctx context.Context, in *Nodes, opts ...grpc.CallOption) (*Nodes, error) {
	out := new(Nodes)
	err := grpc.Invoke(ctx, "/rpb.Raft/ClusterState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) Leave(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := grpc.Invoke(ctx, "/rpb.Raft/Leave", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Raft service

type RaftServer interface {
	AppendEntries(context.Context, *AppendRequest) (*Response, error)
	RequestVote(context.Context, *VoteRequest) (*Response, error)
	Join(context.Context, *Node) (*Nodes, error)
	ClusterState(context.Context, *Nodes) (*Nodes, error)
	Leave(context.Context, *Node) (*Ack, error)
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpb.Raft/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpb.Raft/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpb.Raft/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).Join(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_ClusterState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nodes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).ClusterState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpb.Raft/ClusterState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).ClusterState(ctx, req.(*Nodes))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpb.Raft/Leave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).Leave(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpb.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _Raft_Join_Handler,
		},
		{
			MethodName: "ClusterState",
			Handler:    _Raft_ClusterState_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _Raft_Leave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x53, 0x4b, 0x6e, 0xdb, 0x30,
	0x10, 0x85, 0x2c, 0x29, 0x76, 0x46, 0x49, 0x1a, 0x10, 0x5d, 0x08, 0x46, 0x3f, 0xae, 0x50, 0x04,
	0x46, 0x17, 0x5e, 0xb8, 0x27, 0x30, 0xe2, 0xa0, 0x70, 0x11, 0x74, 0xc1, 0x16, 0xdd, 0xd3, 0xe2,
	0xa4, 0x10, 0x62, 0x91, 0x2c, 0xc9, 0x04, 0xe9, 0x01, 0x7a, 0x9f, 0xde, 0xa4, 0x27, 0xe9, 0x1d,
	0x0a, 0x92, 0x92, 0xc2, 0x18, 0xad, 0x77, 0x33, 0x6f, 0x1e, 0x87, 0xf3, 0x38, 0x8f, 0x00, 0x9a,
	0xdd, 0xd8, 0x85, 0xd2, 0xd2, 0x4a, 0x92, 0x6a, 0xb5, 0xad, 0xd6, 0x90, 0x7f, 0x92, 0x1c, 0x0d,
	0x99, 0xc2, 0xc4, 0xa0, 0xe0, 0xa8, 0x37, 0xeb, 0x32, 0x99, 0x25, 0xf3, 0x8c, 0x0e, 0x39, 0x79,
	0x0d, 0xb9, 0x70, 0xa4, 0x72, 0x34, 0x4b, 0xe7, 0xc5, 0xf2, 0x78, 0xa1, 0xd5, 0x76, 0xe1, 0x8e,
	0xd1, 0x80, 0x57, 0x7f, 0x12, 0x38, 0x5d, 0x29, 0x85, 0x82, 0x53, 0xfc, 0x7e, 0x87, 0xc6, 0x1e,
	0x6c, 0x47, 0x20, 0xb3, 0xa8, 0xdb, 0x72, 0xe4, 0x71, 0x1f, 0x3b, 0xfe, 0x0e, 0x59, 0xe0, 0xa7,
	0x81, 0xdf, 0xe7, 0xe4, 0x15, 0x80, 0xd2, 0x78, 0x7f, 0x2d, 0xbf, 0x6d, 0xf8, 0x43, 0x99, 0xf9,
	0x6a, 0x84, 0x90, 0x19, 0x14, 0x5d, 0xf6, 0xc5, 0xb5, 0xcd, 0x3d, 0x21, 0x86, 0xc8, 0x1c, 0x9e,
	0x85, 0x6e, 0x97, 0xb2, 0x6d, 0x1b, 0xeb, 0xda, 0x1c, 0x79, 0xd6, 0x3e, 0x4c, 0xde, 0xc2, 0x18,
	0x85, 0xd5, 0x0d, 0x9a, 0x72, 0xec, 0xc5, 0x82, 0x17, 0x7b, 0x25, 0xac, 0xfe, 0x41, 0xfb, 0x52,
	0xf5, 0x33, 0x81, 0xe2, 0xab, 0xb4, 0xd8, 0xab, 0xed, 0x15, 0x25, 0x91, 0xa2, 0x19, 0x14, 0x35,
	0x13, 0xbc, 0xe1, 0xcc, 0xe2, 0x66, 0xdd, 0x89, 0x8d, 0x21, 0xa7, 0x6b, 0xc7, 0x8c, 0xed, 0x74,
	0x05, 0xd5, 0x11, 0xe2, 0x3a, 0x74, 0x99, 0xd7, 0x15, 0x84, 0xc7, 0x50, 0xf5, 0x01, 0x72, 0x3f,
	0xd9, 0x3f, 0x07, 0x38, 0x87, 0xb4, 0xe1, 0x0f, 0xdd, 0xc5, 0x2e, 0x24, 0x25, 0x8c, 0x6b, 0xd9,
	0xb6, 0x4c, 0x70, 0x7f, 0xdb, 0x09, 0xed, 0xd3, 0xea, 0x1d, 0x64, 0x6e, 0x9f, 0xe4, 0x0c, 0x46,
	0xc3, 0xc2, 0x46, 0x61, 0x55, 0x8c, 0x73, 0xed, 0x9b, 0x1c, 0x53, 0x1f, 0x57, 0xbf, 0x12, 0x98,
	0x50, 0x34, 0x4a, 0x0a, 0x83, 0x07, 0xf7, 0xfc, 0x1c, 0x72, 0xd4, 0x5a, 0xf6, 0xa7, 0x43, 0xe2,
	0x4e, 0xb0, 0xba, 0x46, 0x65, 0x31, 0x4c, 0x31, 0xa1, 0x43, 0x3e, 0xc8, 0xc8, 0xfe, 0xe3, 0x8c,
	0x7c, 0xcf, 0x19, 0x17, 0x70, 0xe6, 0x9e, 0x63, 0xa5, 0xd4, 0xae, 0x41, 0xfe, 0xb8, 0xd6, 0x3d,
	0xb4, 0x7a, 0x03, 0xe9, 0xaa, 0xbe, 0x3d, 0x34, 0xec, 0xf2, 0x77, 0x02, 0x19, 0x65, 0x37, 0x96,
	0x2c, 0x7b, 0x2b, 0x5f, 0x85, 0x65, 0x13, 0xe2, 0x1d, 0xf0, 0xc4, 0xde, 0xd3, 0x53, 0x8f, 0x0d,
	0xaf, 0xb0, 0x80, 0xa2, 0xab, 0x38, 0x57, 0x90, 0x73, 0x5f, 0x8d, 0x0c, 0xb2, 0xcf, 0x7f, 0x09,
	0xd9, 0x47, 0xd9, 0x08, 0xf2, 0xf8, 0x93, 0xa6, 0x30, 0x84, 0x86, 0x5c, 0xc0, 0xc9, 0xe5, 0xee,
	0xce, 0x58, 0xd4, 0x9f, 0x2d, 0xb3, 0x48, 0xa2, 0xda, 0x13, 0xde, 0x0b, 0xc8, 0xaf, 0x91, 0xdd,
	0x63, 0xdc, 0x67, 0x12, 0xa6, 0xad, 0x6f, 0xb7, 0x47, 0xfe, 0x9b, 0xbf, 0xff, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x6e, 0x86, 0x1b, 0xb1, 0xf4, 0x03, 0x00, 0x00,
}
